version: "3.5"

services:
  dynamodb:
    container_name: user_api_dynamodb
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data:rw
    ports:
      - 8000:8000

networks:
  default:
    name: "user-api"
